<div class="row">
    <div class="col-sm-12">
        <div class="blog-post-area">
            <h2 class="title text-center">Latest From our Blog</h2>
            <div class="single-blog-post">
                <h3><?php echo $page->name ?></h3>
                <div class="post-meta">
                    <ul>
                        <li><i class="fa fa-user"></i> Mac Doe</li>
                        <li><i class="fa fa-clock-o"></i> 1:33 pm</li>
                        <li><i class="fa fa-calendar"></i> DEC 5, 2013</li>
                    </ul>
                </div>
                <?php echo $page->content ?>
            </div>
        </div>
        <!--/blog-post-area-->
    </div>
</div>
