<?php echo $this->getContent() ?>
<ul class="pager">
    <li class="previous pull-left">
        <?php
echo $this->tag->linkTo("profile/index", "&larr; Назад")
?>
    </li>
</ul>
<form method="post" autocomplete="off" action="/profile/index/changePassword">

    <div class="center scaffold">

        <h2>Сменить пароль</h2>

        <div class="clearfix">
            <label for="password">Пароль</label>
<?php echo $form->render("password") ?>
        </div>

        <div class="clearfix">
            <label for="confirmPassword">Подтвердить пароль</label>
            <?php echo $form->render("confirmPassword") ?>
        </div>
        <hr />
              <div class="form-actions">
            <?php echo $this->tag->submitButton(array(
  "Сохранить",
  "class" => "btn btn-success",
  //"onclick" => "return ChangePass.validate();",
  )) ?>
        </div>

    </div>

</form>