<div class="row clearfix">
<div class="col-md-12 column">
<nav class="navbar navbar-default" role="navigation">
				<div class="navbar-header">
					 <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="/index">На сайт</a>
				</div>
				
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li>
							<a href="/profile/index">Общая информация</a>
						</li>
                        <li>
                            <a href="/profile/orders">Мои заказы</a>
                        </li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li class="dropdown">
							 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Профиль<strong class="caret"></strong></a>
							<ul class="dropdown-menu">
                <?php if($auth['role_id'] < 4)
               { echo 
								'<li>
									<a href="/backend/category">Админка</a>
								</li>'; } ?>
								<li class="divider"></li>
								<li>
									<a href="/session/logout">Выход</a>
								</li>
							</ul>
						</li>
					</ul>
				</div>				
</nav>
</div>
</div>