<div id="search-category-attributes" class="searchProductsBlock">
    <h2><?php echo $category ? $category->title . ' attributes' : 'Attributes' ?></h2>
    <table class="table table-striped table-condensed">
        <thead>
            <tr>
                <th>name</th>
                <th>value</th>
            </tr>
        </thead>
        <tbody>
            <?php list($attributes, $attributeValues)=$category->getAttributesForSearchBlock(); ?>
            <?php foreach($attributes as $attribute): ?>
            <tr>
                <td>
                    <?php echo $attribute[ 'name'] . ':' ?>
                </td>
                <td>
                    <select id="<?php echo $attribute['name'] ?>" class="select2 attributeValues" name="<?php echo 'attributes['.$attribute['name'].']' ?>">
                        <option value=""> </option>
                        <?php foreach ($attributeValues[$attribute[ 'name']] as $key=> $value): ?>
                        <option value="<?php echo $key ?>">
                            <?php echo $value ?>
                        </option>
                        <?php endforeach; ?>
                    </select>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
