<div class="left-sidebar">
    <h2>Category</h2>
    <div id="categories-container"></div>
    <!--/category-products-->
    <?php if($category): ?>
    <!-- block for filtering products -->
    <div class="brands_products">
        <!--brands_products-->
        <h2>Brands</h2>
        <div class="brands-name searchProductsBlock">
            <ul class="list-group nav nav-pills nav-stacked">
                <li class="list-group-item">
                    <?php echo $this->tag->selectStatic(["brands", 'name' => "brands[]", "class" => "select2", "multiple" => "multiple", $brands, 'useEmpty' => true, 'emptyText' => '&nbsp;', 'emptyValue' => '0']); ?>
                </li>
            </ul>
        </div>
    </div>
    <!--/brands_products-->
    <br />
    <div class="price-range searchProductsBlock">
        <!--price-range-->
        <h2>Price Range</h2>
        <div id="priceRangeSlider" data-slider-min="0" data-slider-max="<?php echo $maxPrice ?>" data-slider-step="5" data-slider-value="[0, <?php echo $maxPrice ?>]"></div>
        <br />
        <span class="pull-left">$&nbsp;</span><span class="pull-left"><input type="text" name="price['min']" id="priceRangeLeftValue" /></span><span class="pull-right"><input type="text" name="price['max']" id="priceRangeRightValue" /></span><span class="pull-right">$&nbsp;</span>
    </div>
    <hr />
    <!--/price-range-->
    <div id="search-category-attributes" class="searchProductsBlock">
        <h2><?php echo $category ? $category->title . ' attributes' : 'Attributes' ?></h2>
        <table class="table table-striped table-condensed">
            <thead>
                <tr>
                    <th>name</th>
                    <th>value</th>
                    <th>suffix</th>
                </tr>
            </thead>
            <tbody>
                <?php list($attributes, $attributeValues)=$category->getAttributesForSearchBlock(); ?>
                <?php foreach($attributes as $attribute): ?>
                <tr>
                    <td>
                        <?php echo $attribute[ 'name'] . ':' ?>
                    </td>
                    <td>
                        <?php echo $this->tag->selectStatic([$attribute['name'], 'name' => 'attributes['.$attribute['name'].']', "class" => "select2 attributeValues", $attributeValues[$attribute['name']]]); ?>
                    </td>
                    <td>
                        <?php echo $attribute[ 'template'] ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <button id="searchProductsButton" class="btn btn-info pull-right">Make Search</button>
    <?php endif; ?>
    <!-- /block for filtering products -->
</div>
