<?php echo $this->getContent() ?>
<ul class="pager">
    <li class="previous pull-left">
        <?php echo $this->tag->linkTo("profile/index", "&larr; Go Back") ?>
    </li>
</ul>
<form method="post" autocomplete="off" action="/profile/changePassword">

    <div class="center scaffold">

        <h2>Change password</h2>

        <div class="clearfix">
            <label for="password">Password</label>
            <?php echo $form->render("password") ?>
            <?php foreach ($form->getMessagesFor('password') as $message) { echo $message; } ?>
        </div>

        <div class="clearfix">
            <label for="confirmPassword">Confirm password</label>
            <?php echo $form->render("confirmPassword") ?>
            <?php foreach ($form->getMessagesFor('confirmPassword') as $message) { echo $message; } ?>
        </div>
        <hr />
        <div class="form-actions">
            <?php echo $form->render('Save'); ?>
        </div>

    </div>
    <?php echo $form->render("csrf", array("value" => $this->security->getToken())) ?>
    <?php foreach ($form->getMessagesFor('csrf') as $message) { echo $message; } ?>

    <hr/>

</form>
