<?php echo $this->getContent() ?>

<div align="center">
    <?php echo $this->tag->form(["profile/edit", "id" => "editProfileForm", "autocomplete" => "on" ]) ?>

    <div align="left">
        <h4>Edit Profile</h4>
    </div>

    <table class="signup table">
        <tr>
            <td align="right">
                <?php echo $form->label("name") ?></td>
            <td>
                <?php echo $form->render("name") ?>
                <?php foreach ($form->getMessagesFor('name') as $message) { echo $message, '
                <br>'; } ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <?php echo $form->label("email") ?></td>
            <td>
                <?php echo $form->render("email") ?>
                <?php foreach ($form->getMessagesFor('email') as $message) { echo $message, '
                <br>'; } ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <?php echo $form->label("address") ?></td>
            <td>
                <?php echo $form->render("address") ?>
                <?php foreach ($form->getMessagesFor('address') as $message) { echo $message, '
                <br>'; } ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <?php echo $form->label("phone") ?></td>
            <td>
                <?php echo $form->render("phone") ?>
                <?php foreach ($form->getMessagesFor('phone') as $message) { echo $message, '
                <br>'; } ?>
            </td>
        </tr>
        <tr>
            <td align="right"></td>
            <td>
                <?php echo $form->render("Save"); ?>
            </td>
        </tr>
    </table>

    <?php echo $form->render("csrf", array("value" => $this->security->getToken())) ?>
    <?php foreach ($form->getMessagesFor('csrf') as $message) { echo $message, '
    <br>'; } ?>

    <hr/>

    <?php echo $this->tag->endForm(); ?>

</div>
