<div class="row">
    <div class="col-sm-4">
        <?php $this->view->partial('partials/leftSideBar'); ?>
    </div>
    <div class="col-sm-8 padding-right">
        <div class="features_items">
            <!--features_items-->
            <h2 class="title text-center"><?php echo $category ? $category->title : 'Feature Items'  ?></h2>
            <div id="productsList">
                <?php $this->view->partial('catalog/_list'); ?></div>
        </div>
        <!--features_items-->
    </div>
</div>
<div style="display: none" id="categories-tree-source">
    <?php echo $categories ?>
</div>
