<tbody>
    <tr>
        <td style="padding:40px 0  0 0;">
            <p style="color:#000;font-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">

                <h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">You're Almost There! Just Confirm Your Email</h2>

                <div style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">
                    <p>You have successfully created an account on the site Phasty e-commerce.</p>
                    <p>Please click on the link below to confirm your email address and activate your account.</p>

                    <br />
                    <br />
                    <a target="_blank" style="background:#E86537;color:#fff;padding:10px" href="http://<?php echo $publicUrl.$confirmUrl; ?>">Confirm</a>

                    <br />
                    <br />
                    <p>If you believe that received the email in error, please ignore this message. Kind regards.</p>
                    <br />
                </div>
        </td>
    </tr>
</tbody>
