<tbody>
    <tr>
        <td style="padding:40px 0  0 0;">
            <p style="color:#000;font-size: 16px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;font-weight:normal;">

                <h2 style="font-size: 14px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">Reset Your Password</h2>

                <p style="font-size: 13px;line-height:24px;font-family:'HelveticaNeue','Helvetica Neue',Helvetica,Arial,sans-serif;">
                    <p>Follow the link below to change the password to your personal account on the site Phasty e-commerce.If you do not want to change your password simply leave this email without attention.</p>
                    <br />
                    <br />
                    <a target="_blank" style="background:#E86537;color:#fff;padding:10px" href="http://<?php echo $publicUrl.$resetUrl; ?>">Change password</a>

                    <br />
                    <br />

                    <br />
                </p>
        </td>
    </tr>
</tbody>
