<div class="container text-center">
    <div class="logo-404">
        <a href="index.html"><img src="/img/logo.png" alt="" /></a>
    </div>
    <div class="content-404">
        <img src="/img/404/404.png" class="img-responsive" alt="" />
        <h1><b>OPPS!</b> We Couldn’t Find this Page</h1>
        <p>Uh... So it looks like you brock something. The page you are looking for has up and Vanished.</p>
        <h2><?php echo $this->tag->linkTo(["index/index", "Bring me back Home"]); ?></h2>
    </div>
</div>
