<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php echo $this->tag->getTitle() ?>
    <meta name="description" content="E-commerce Catalog on PhalconPhp" />
    <meta name="author" content="Alex Nikitin" />
    <title>Home | E-Shopper</title>
    <link href="/css/common/bootstrap.min.css" rel="stylesheet">
    <link href="/css/common/font-awesome.min.css" rel="stylesheet">
    <link href="/css/common/select2.min.css" rel="stylesheet">
    <link href="/css/front/prettyPhoto.css" rel="stylesheet">
    <link href="/css/front/jquery.nouislider.min.css" rel="stylesheet">
    <link href="/css/front/animate.css" rel="stylesheet">
    <link href="/css/front/main.css" rel="stylesheet">
    <link href="/css/front/responsive.css" rel="stylesheet">
    <link href="/vendor/toastr/toastr.min.css" rel="stylesheet">
    <link href="/css/front/product-slider.css" rel="stylesheet">
    <link href="/css/front/custom.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="/jsfront/html5shiv.js"></script>
    <script src="/jsfront/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="favicon.ico">
</head>
<!--/head-->

<body>
    <?php echo $this->getContent() ?>
    <script src="/jsFront/jquery-1.11.2.min.js"></script>
    <script src="/jsFront/bootstrap.min.js"></script>
    <script src="/jsFront/select2.min.js"></script>
    <script src="/jsFront/jquery.nouislider.all.min.js"></script>
    <script src="/jsFront/jquery.prettyPhoto.js"></script>
    <script src="/vendor/toastr/toastr.min.js"></script>
    <script src="/jsFront/product-slider.js"></script>
    <script src="/jsFront/jRate.min.js"></script>
    <script src="/jsFront/main.js"></script>
</body>

</html>
